package com.services.skills.Enums;

public enum FieldEnums {
    COMMUNICATION,
    PROBLEM_SOLVING,
    TEAMWORK,
    TIME_MANAGEMENT,
    LEADERSHIP,
    ADAPTABILITY,
    CREATIVITY,
    CRITICAL_THINKING,
    ATTENTION_TO_DETAIL,
    ORGANIZATION,
    DECISION_MAKING,
    ACTIVE_LISTENING,
    CONFLICT_RESOLUTION,
    EMOTIONAL_INTELLIGENCE,
    INTERPERSONAL_SKILLS,
    PRESENTATION_SKILLS,
    PLANNING,
    STRATEGIC_THINKING,
    INNOVATION,
    CUSTOMER_SERVICE,
    IT
}
